### ISSUE TITLE
Functions to get local network information

### ISSUE THREAD

**Issue by MKV21** [HSAnet/glimpse_client#203]
For networkhelper.h/cpp:

- [x] localIpAddress()
- [x] publicIpAddress()
- [x] gatewayIpAddress()
- [ ] dnsServerIpAddress()

**Comment by monstermunchkin** [comment]
So, there is no built-in command for determining the public IP address as we already know. The easiest solution would be a web request to e.g. icanhazip.com. Now, web requests in Qt are unfortunately asynchronous, but we'd need a synchronous version, right?! How do we achieve that without using hacks like [this](http://stackoverflow.com/a/17410327)?
The other solution would be for our app to depend on something like *curl*, and then simply call `curl icanhazip.com`.
What are your thoughts on both of these ideas?

**Comment by monstermunchkin** [comment]
@theoriginalgri, would you mind implementing the OS X part of the DNS server lookup?

**Comment by MKV21** [comment]
This might come as a shock, but @theoriginalgri has finished his Bachelor and no longer works for us ;) He could do this on his own time but I guess he has other work to do. 

Can you ( @monstermunchkin ) write the initial code and let @Pflanzgurke test/finish it?

**Comment by theoriginalgri** [comment]
It might be another shock but we already had some of these functions but @MKV21 did not know about them :)

https://github.com/HSAnet/glimpse_client/blob/develop/src/libclient/connectiontester.cpp#L182
