### ISSUE TITLE
New data storage

### ISSUE THREAD

**Issue by theoriginalgri** [HSAnet/glimpse_client#21]
Currently there are classes like TestDefinition which are created once by the data storage (SchedulerStorage) and then passed on by smart pointers.

This prevents us from safely changing those values. 

A better way would be to have only id values for each type. These id values are used to identify and find small data containers that can be copied or cached safely. Any modification is done via the data storage again using the id and a changed object. This approach also allows us to enumerate all tasks without actually loading them into the program. Also read and write operations can be batched together using a working set (class that caches these operations).

**Comment by MKV21** [comment]
- store json files
- one file per TaskId per day
- user setting: store last N days (defaults to 10)
- don't save the localinformation (pre/post-info)

**Comment by MKV21** [comment]
https://github.com/HSAnet/glimpse_client/blob/develop/src/libclient/storage/storagepaths_android.cpp#L43 references function that does not exist in the java code (https://github.com/HSAnet/glimpse_client/blob/develop/src/mobile/android/src/StorageHelper.java)
