### ISSUE TITLE
[Buildserver] Debian and Arch-Linux packages

### ISSUE THREAD

**Issue by MKV21** [HSAnet/glimpse_client#240]
We need to automatically build and distribute packages for those two. If I remember correctly there are some system service scripts missing?

**Comment by MKV21** [comment]
What's the status on this? @monstermunchkin @theoriginalgri

**Comment by monstermunchkin** [comment]
I will be adding _glimpse-git_, and perhaps also _glimpse_, to the AUR soon-ish as soon as I have figured out all of the dependencies for Arch Linux.

**Comment by monstermunchkin** [comment]
https://aur.archlinux.org/packages/glimpse-git/

**Comment by MKV21** [comment]
pkgver=2.3.5.9.g550d6e1

What is the 9 and the hash?

**Comment by monstermunchkin** [comment]
The [VCS package guidelines](https://wiki.archlinux.org/index.php/VCS_package_guidelines) recommend using a [`pkgver()`](https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver.28.29_function) function. From [git-describe (1)](https://www.kernel.org/pub/software/scm/git/docs/git-describe.html):
 > [...] the most recent tag that is reachable from a commit. If the tag points to the commit, then only the tag is shown. Otherwise, it suffixes the tag name with the number of additional commits on top of the tagged object and the abbreviated object name of the most recent commit.

So, the there would be 9 additional commits on top of the tagged object (2.3.5), and the hash is the abbreviated object name of the most recent commit. To avoid confusion, we could adopt a versioning schema using `r9`, i.e.`2.3.5.r9.g550d6e1`.

**Comment by MKV21** [comment]
Okay, thanks. Make it so! ;)
