### ISSUE TITLE
glimpse-console: exit on registration

### ISSUE THREAD

**Issue by monstermunchkin** [HSAnet/glimpse_client#290]
What I want to be able to do:
```bash
docker run -v /home/glimpse/.local/share/HS-Augsburg -v /home/glimpse/.config/HS-Augsburg --name glimpse-data busybox
docker run --volumes-from glimpse-data --rm monstermunchkin/glimpse --register-anonymous
docker run --volumes-from glimpse-data -d --name glimpse monstermunchkin/glimpse
```
The problem is that `--register-anonymous` doesn't exit and I would have to stop/kill the glimpse container manually before being able to continue with step 3. I propose that we change the behaviour of `--register-anonymous` and let it exit after registering. Would that be in any way inconvenient?

**Comment by theoriginalgri** [comment]
I don't see why this would be a problem.

Otherwise we could add a ```--exit-after-registration``` parameter or something with a better name to express the same?

@MKV21 any comments?

**Comment by MKV21** [comment]
I thought about adding a --oneshot parameter (or something like that) some months ago. I don't have a problem if you add this and exit the client after some seconds if the parameter is set. But come up with a better name, please!

**Comment by monstermunchkin** [comment]
Simply exiting by default is not an option then? It would result in the least code changes after all.

**Comment by MKV21** [comment]
Hm okay, automatically exiting after --register and --register-anonymous.

**Comment by MKV21** [comment]
closed by d47418
