### ISSUE TITLE
Windows build error

### ISSUE THREAD

**Issue by monstermunchkin** [HSAnet/glimpse_client#311]
I cannot seem to build the project on Windows as I get the following error
```
Project ERROR: Unknown module(s) in QT: systeminfo
```
Is there a trick, @theoriginalgri ? It has to work somehow since the build server doesn't have any problems with it.

**Comment by MKV21** [comment]
@theoriginalgri has no idea, the build server is working. Have you figured this out yet? Did you init and upgrade the submodules?

**Comment by monstermunchkin** [comment]
QtSystemInfo had to be installed manually as it was not installed alongside the other components.
