### ISSUE TITLE
Synchronize local time of probe with a ntp server

### ISSUE THREAD

**Issue by MKV21** [HSAnet/glimpse_client#83]
Get the time offset at probe-start-time and use it for the execution of schedules.

**Comment by theoriginalgri** [comment]
A way to find out the ntp server for the local network might also be a good point.

The "not working" fact might also only happen in our local network since we're only allowed to use time.hs-augsburg.de and no other server from outside.

```
root@rack39:~# ntpdate time.hs-augsburg.de
10 Feb 16:00:28 ntpdate[4477]: adjust time server 141.82.25.204 offset 0.001826 sec

root@rack39:~# ntpdate ptbtime1.ptb.de
10 Feb 16:00:52 ntpdate[4479]: no server suitable for synchronization found

root@rack39:~# ntpdate time.nist.gov
10 Feb 16:01:15 ntpdate[4481]: no server suitable for synchronization found
```

**Comment by MKV21** [comment]
Don't use Q_GLOBAL_STATIC, this is not working for this functionality.

**Comment by MKV21** [comment]
Fixed by @monstermunchkin , open another issue for the local ntp server thing.
